// Copyright 2022 Shurygina A

#ifndef   MODULES_SHURYGINA_REV_POL_NOTAT_INCLUDE_QUEUE_H_
#define   MODULES_SHURYGINA_REV_POL_NOTAT_INCLUDE_QUEUE_H_

#endif  //   MODULES_SHURYGINA_REV_POL_NOTAT_INCLUDE_QUEUE_H_

